# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: gateway

spring:
  application:
    name: gateway

  # cloud:
  #   gateway:
  #     routes:
  #       - id: USERSERVICE
  #         uri: http://localhost:18081
  #         predicates:
  #           - Path=/ms1/**
            
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://auser:password1!@localhost:8761/eureka



